### ISSUE TITLE
Version 3.26.x updates

### ISSUE THREAD

**Issue by kirantpatil** [patternfly/patternfly-sass#154]
Hi,

Last 4 months, no update to the project.

Current up stream is at 3.26.1.

What is holding back to the updates ?

Are you expecting to Rails 5.1 feature to install by "yarn" ?

Please let us know how to install latest version ?

Thanks,
Kiran.

**Comment by skateman** [comment]
Hi,

there are some issues with converting the newer releases and I'm currently discussing it with the upstream team. We provide an NPM package, so it *should be* installable using yarn out of the box.

**Comment by wgordon17** [comment]
Has there been any progress on this?

**Comment by skateman** [comment]
@wgordon17 the patternfly core team is taking over the SASS development, they're currently integrating it to the core repo.
