### ISSUE TITLE
Inconsistent lighten() between LESS and SASS

### ISSUE THREAD

**Issue by skateman** [patternfly/patternfly-sass#28]
If the `TOLERANCE` in the tests is set to `0.00` and the waiting time in `capture.js` is over *800ms*, only the pages with navbars are failing on the comparison. After a short research I figured out that the problem is that the lighten() function called from [SASS](https://github.com/patternfly/patternfly-sass/blob/master/sass/_variables.scss#L63) returns different output than in [LESS](https://github.com/patternfly/patternfly/blob/master/less/variables.less#L63).

**Comment by skateman** [comment]
@himdel !!

**Comment by awood** [comment]
Fixed in SASS 3.4.15 once it releases.

**Comment by skateman** [comment]
https://github.com/sass/sass/commit/14ec0d077bcc57f480f482c4fab6b9042153c047
