### ISSUE TITLE
Add Bower support?

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-sass#66]
I'm forwarding the following email sent to the PatternFly list on behalf of Kanagaraj.  The same request was made in the PatternFly IRC channel yesterday.

--------

Hi All,

Looks like https://github.com/patternfly/patternfly-sass can not be installed through bower. 

Since "patternfly-sass's converter is a fork of bootstrap-sass", is there a possibility of supporting bower install?

 bootstrap-sass supports bower - https://github.com/twbs/bootstrap-sass#c-bower

Thanks,
Kanagaraj

**Comment by skateman** [comment]
My bad, forgot to comment those stuff out. But eventually we will support bower :)

**Comment by kmkanagaraj** [comment]
Any update on when will this be out? 
Also nice to have it installed through npm.

**Comment by skateman** [comment]
https://github.com/patternfly/patternfly-sass/issues/70

**Comment by skateman** [comment]
```bash
Package patternfly-sass registered successfully!
All valid semver tags on git://github.com/patternfly/patternfly-sass.git will be available as versions.
To publish a new version, just release a valid semver tag.

Run bower info patternfly-sass to list the available versions.
```
