### ISSUE TITLE
Publish via npm

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-sass#70]
Since we're publishing PatternFly via Bower and NPM, it probably makes sense to do the same for PatternFly-sass.  Make is so, number one?

**Comment by bleathem** [comment]
:+1:

**Comment by bleathem** [comment]
... bump ...

**Comment by priley86** [comment]
+1 would love to see this 👍

**Comment by skateman** [comment]
https://github.com/patternfly/patternfly-sass/commit/4560880ececd788ee7773412a425a189807af106
