### ISSUE TITLE
v2.3.0 release

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-sass#84]
https://github.com/patternfly/patternfly/releases/tag/v2.3.0 is out, so it seems that the equivalent release should exist for patternfly-sass.

patternfly has adopted a two week release cadence, so plan on much more frequent releases, @skateman.  :)

**Comment by skateman** [comment]
@rhamilto I'm working on it, but there are some issues with `bootstrap-switch`, ping me on IRC!
