### ISSUE TITLE
More than 4 parameters in assets/stylesheets/patternfly/_pagination.scss

### ISSUE THREAD

**Issue by carlosthe19916** [patternfly/patternfly-sass#89]
I imported patternfly in my yeoman proyect, but the compiler found a error as:

error app/styles/main.scss (Line 53 of bower_components/patternfly-sass/assets/stylesheets/patternfly/_pagination.scss: Mixin pagination-size takes 4 arguments but 5 were passed.)

this error is in (bootstrap just have 4 parameters in there, why patternfly pass 5 parameters?):

PATTERNFLY IS:
@include pagination-size($padding-small-vertical, $padding-small-horizontal, $font-size-small, $line-height-small, $border-radius-small);

AND IN BOOTSTRAP IS:
@include pagination-size($padding-small-vertical, $padding-small-horizontal, $font-size-small, $border-radius-small);

**Comment by skateman** [comment]
I remember this issue from earlier versions, which version of Bootstrap are you using?

**Comment by carlosthe19916** [comment]
I'm using bootstrap 3.2.0. Which version of bootstraop i should use?

**Comment by skateman** [comment]
@carlosthe19916 the [latest](https://github.com/patternfly/patternfly-sass/releases/tag/v2.6.0) release requires [~> 3.3.5](https://github.com/patternfly/patternfly-sass/blob/master/patternfly-sass.gemspec#L15).

**Comment by carlosthe19916** [comment]
Thank you very much

**Comment by skateman** [comment]
Enjoy using patternfly and feel free to report other issues if you find any!
